"""Add name column to influencers table

Revision ID: 514d204da1c2
Revises: e39fb876edc6
Create Date: 2025-04-08 14:07:14.824936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514d204da1c2'
down_revision: Union[str, None] = 'e39fb876edc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencers', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencers', 'name')
    # ### end Alembic commands ###
