"""Added error_code and error_reason

Revision ID: e39fb876edc6
Revises: 
Create Date: 2025-04-01 02:01:48.551304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39fb876edc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencers', sa.Column('message_sent_at', sa.DateTime(), nullable=True))
    op.add_column('influencers', sa.Column('error_code', sa.String(), nullable=True))
    op.add_column('influencers', sa.Column('error_reason', sa.String(), nullable=True))
    op.add_column('influencers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('influencers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencers', 'updated_at')
    op.drop_column('influencers', 'created_at')
    op.drop_column('influencers', 'error_reason')
    op.drop_column('influencers', 'error_code')
    op.drop_column('influencers', 'message_sent_at')
    # ### end Alembic commands ###
